### ISSUE TITLE
KeyError: "Unable to open object (object 'conf_idx' doesn't exist)"

### ISSUE THREAD

**Issue by hitdpc** [ratschlab/spladder#71]
Hi,I'm running spladder_test.py.This is my command line:
python spladder_test.py  --labelA='JIA' --labelB='hc' -n 81  --parallel=26 -D y  -a $bam1 -b $bam2 -o $path  1>1.log 2>1.err
And I get an error like this 'KeyError: "Unable to open object (object 'conf_idx' doesn't exist)" '.
And my event files format is like this:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/41619935/47626957-a2403a00-db68-11e8-81fc-515c25158bfa.png">
My first row is 'confirmed',not 'conf_idx'

**Comment by andjedid** [comment]
Hi !

Did you figure out what was the problem ?

I think I have the same one. 
I ran this command :
python spladder_test.py --outdir output_path --validate_sg n --matlab n --conditionA path_to_bam1,path_to_bam2,path_to_bam3 --conditionB path_to_bam4,path_to_bam5,path_to_bam36 --readlen 50 --labelA condA --labelB condB

And I got this error : 
/project/6007495/singularity/1.1.0/builtin/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/project/6007495/singularity/1.1.0/builtin/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/project/6007495/singularity/1.1.0/builtin/anaconda/lib/python2.7/site-packages/numpy/lib/scimath.py:120: RuntimeWarning: invalid value encountered in less
  if any(isreal(x) & (x < 0)):
/project/6007495/singularity/1.1.0/builtin/anaconda/lib/python2.7/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
Traceback (most recent call last):
  File "/project/6007495/adjedid/softwares/spladder-master/python/spladder_test.py", line 1052, in <module>
    main()
  File "/project/6007495/adjedid/softwares/spladder-master/python/spladder_test.py", line 851, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], idx1, idx2, event_type, CFG, gen_event_ids=False, low_mem=CFG['low_memory'])
  File "/project/6007495/adjedid/softwares/spladder-master/python/modules/alt_splice/quantify.py", line 403, in quantify_from_counted_events
    conf_idx = IN['conf_idx'][:].astype('int')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/project/6007495/singularity/1.1.0/builtin/anaconda/lib/python2.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'conf_idx' doesn't exist)"

Is my command not right ? 

Thanks for your help !

**Comment by akahles** [comment]
Apologies for the late reply. I am currently porting SplAdder to Python3 In the course of this, I will also address the above issue and hopefully be able to resolve it quickly.
Best,
Andre

**Comment by jfass** [comment]
Hi Andre,

I'm hitting this same error message:

```
Traceback (most recent call last):
  File "/home/ubuntu/ALTSPLICE/spladder-venv/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/ALTSPLICE/spladder-venv/lib/python3.5/site-packages/spladder/spladder.py", line 191, in main
    options.func(options)
  File "/home/ubuntu/ALTSPLICE/spladder-venv/lib/python3.5/site-packages/spladder/spladder_test.py", line 671, in spladder_test
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(options.fname_events, idx1_all, idx2_all, event_type, options, gen_event_ids=False, high_mem=options.high_memory)
  File "/home/ubuntu/ALTSPLICE/spladder-venv/lib/python3.5/site-packages/spladder/alt_splice/quantify.py", line 282, in quantify_from_counted_events
    conf_idx = IN['conf_idx'][:].astype('int')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ubuntu/ALTSPLICE/spladder-venv/lib/python3.5/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'conf_idx' doesn't exist)"
```

Has it been resolved in a recent commit?

Thanks,
~Joe

**Comment by akahles** [comment]
Hi Joe,
Thanks for reporting. I am currently traveling and will have a look at this as soon as possible.
Cheers,
Andre

**Comment by akahles** [comment]
This issue occurs, when SplAdder has found no events but testing of samples is invoked. I have changed the code, such the program handles these cases gracefully and no longer crashes. 

The change will be part of the next release, but is already available in the development branch.

Cheers,

Andre

**Comment by akahles** [comment]
Released version 2.2.1. Please re-open if issue still occurs.

**Comment by paulinefx** [comment]
Hello,

I have the same error. I installed spladder 2.2.2 via pip, I'm on python 3.6.3 and running on CentOS 7.6.1810.

This is my error :

```
Traceback (most recent call last):
  File "/data/home/hfx405/python3.6.3-virtual-environments/env/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/data/home/hfx405/python3.6.3-virtual-environments/env/lib/python3.6/site-packages/spladder/spladder.py", line 195, in main
    options.func(options)
  File "/data/home/hfx405/python3.6.3-virtual-environments/env/lib/python3.6/site-packages/spladder/spladder_build.py", line 152, in spladder
    spladder_core(options)
  File "/data/home/hfx405/python3.6.3-virtual-environments/env/lib/python3.6/site-packages/spladder/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, options)
  File "/data/home/hfx405/python3.6.3-virtual-environments/env/lib/python3.6/site-packages/spladder/core/gen_graphs.py", line 106, in gen_graphs
    genes, inserted_ = insert_cassette_exons(genes, options)
  File "/data/home/hfx405/python3.6.3-virtual-environments/env/lib/python3.6/site-packages/spladder/editgraph.py", line 863, in insert_cassette_exons
    [tracks] = add_reads_from_sparse_bam(gg, options.bam_fnames, contig, options.confidence, types=['exon_track'], filter=options.read_filter, cache=bam_cache, unstranded=True)
  File "/data/home/hfx405/python3.6.3-virtual-environments/env/lib/python3.6/site-packages/spladder/reads.py", line 284, in add_reads_from_sparse_bam
    cache['reads'] = scipy.sparse.coo_matrix((IN[contig + '_reads_dat'][:], (IN[contig + '_reads_row'][:], IN[contig + '_reads_col'][:])), shape=IN[contig + '_reads_shp'][:], dtype='uint32').tocsc()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/data/home/hfx405/python3.6.3-virtual-environments/env/lib/python3.6/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'chr12_reads_dat' doesn't exist)"
```

Could it be because I am using a more recent python version or because I am using a virtual environment ?

Thanks,
Pauline
