### ISSUE TITLE
Error in build, in event detection

### ISSUE THREAD

**Issue by jfass** [ratschlab/spladder#99]
* spladder version: 2.2.3
* Python version: 3.5
* Operating System: Ubuntu 16

Hi Andre, (starting a new Issue as you suggested) ... this afternoon I cloned and built the repo (and I'm seeing the 2.2.3 tag), and I'm getting:

```
$ cat chr6.eventCalling.err
Traceback (most recent call last):
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/bin/spladder", line 11, in <module>
    load_entry_point('spladder==2.2.3', 'console_scripts', 'spladder')()
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder-2.2.3-py3.5.egg/spladder/spladder.py", line 10, in <module>
    from .spladder_test import spladder_test
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder-2.2.3-py3.5.egg/spladder/spladder_test.py", line 3, in <module>
    import statsmodels.api as sm
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/statsmodels-0.10.1-py3.5-linux-x86_64.egg/statsmodels/api.py", line 3, in <module>
    from . import iolib
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/statsmodels-0.10.1-py3.5-linux-x86_64.egg/statsmodels/iolib/__init__.py", line 1, in <module>
    from .foreign import StataReader, genfromdta, savetxt
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/statsmodels-0.10.1-py3.5-linux-x86_64.egg/statsmodels/iolib/foreign.py", line 14, in <module>
    from statsmodels.compat.python import (zip, lzip, lmap, lrange, string_types, long, lfilter,
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/statsmodels-0.10.1-py3.5-linux-x86_64.egg/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/statsmodels-0.10.1-py3.5-linux-x86_64.egg/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/statsmodels-0.10.1-py3.5-linux-x86_64.egg/statsmodels/tools/tools.py", line 7, in <module>
    import pandas as pd
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pandas-0.25.1-py3.5-linux-x86_64.egg/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pandas-0.25.1-py3.5-linux-x86_64.egg/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pandas-0.25.1-py3.5-linux-x86_64.egg/pandas/core/arrays/__init__.py", line 1, in <module>
    from .array_ import array  # noqa: F401
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pandas-0.25.1-py3.5-linux-x86_64.egg/pandas/core/arrays/array_.py", line 7, in <module>
    from pandas.core.dtypes.common import (
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pandas-0.25.1-py3.5-linux-x86_64.egg/pandas/core/dtypes/common.py", line 11, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pandas-0.25.1-py3.5-linux-x86_64.egg/pandas/core/dtypes/dtypes.py", line 53, in <module>
    class Registry:
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/pandas-0.25.1-py3.5-linux-x86_64.egg/pandas/core/dtypes/dtypes.py", line 84, in Registry
    self, dtype: Union[Type[ExtensionDtype], str]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

From the last step:

```
cat chrList.txt | while read chr; do
  spladder build -o spladder_out.${chr} -a gencode.v19.annotation.pc.${chr}.gtf \
    -b $allbams --parallel 2 -c 0 --set-mm-tag nM --readlen 150 \
    --event-types exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skips \
    --verbose 2>${chr}.eventCalling.err 1>${chr}.eventCalling.out &
done
```

This was in a fresh virtual environment ... cloning and running 'make install' after activating the environment. You mentioned seeing environment issues in the Traceback above? How should I address that ..?

I'm running on ~35 samples, separated by chromosome, just to remind you.

Thanks!

~Joe

**Comment by akahles** [comment]
Hi Joe,

thanks for opening a new issue. 

Could you please check one thing? Can you change into the virtual environment and open up python and try:
```
import statsmodels.api
```
Does this generate the same error?

Thanks,

Andre

**Comment by jfass** [comment]
Aha! yes it does ... maybe I'll blow away the venv, create a new one, 'pip install statsmodels', _then_ clone and build spladder? Let me know if that's not the best way to go ...
TY,
~Joe

**Comment by akahles** [comment]
Yes, sounds good. Also, if you install spladder anew, there was some issue with the version naming on PyPi. I had to regenerate the version 2.2.3, so now you would need to do:
```
pip install spladder==2.2.3b
```
I am also planning on pushing 2.2.4 over the weekend, which should resolve that issue.

**Comment by jfass** [comment]
Awesome!
They're running now ... I'm getting a few of these:

```
Traceback (most recent call last):
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder/spladder.py", line 195, in main
    options.func(options)
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder/spladder_build.py", line 253, in spladder
    analyze_events(options, options.event_types[e_idx])
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder/alt_splice/analyze.py", line 104, in analyze_events
    (events_all, counts) = verify_all_events(events_all, sp.arange(len(options.strains)), options.bam_fnames, event_type, options)
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder/alt_splice/verify.py", line 445, in verify_all_events
    gene_ids_segs = IN['gene_ids_segs'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'gene_ids_segs' doesn't exist)"
```

... but are they just from chromosomes that don't have one of the event types?

**Comment by akahles** [comment]
This should be caused by the same bug as #97 . I fixed this in the latest release 2.3.0. Please re-open if the problem still occurs.

**Comment by jfass** [comment]
Hey Andre,

I hope I'm commenting on the right issue :)

So I'm re-running the event calling step (after qmode single and qmode collect steps), and still getting the same thing:

```
$ cat chr3.eventCalling.err 
Traceback (most recent call last):
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder/spladder.py", line 188, in main
    options.func(options)
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder/spladder_build.py", line 253, in spladder
    analyze_events(options, options.event_types[e_idx])
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder/alt_splice/analyze.py", line 104, in analyze_events
    (events_all, counts) = verify_all_events(events_all, sp.arange(len(options.strains)), options.bam_fnames, event_type, options)
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/spladder/alt_splice/verify.py", line 445, in verify_all_events
    gene_ids_segs = IN['gene_ids_segs'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ubuntu/spladder/spladder-2.2.3-venv/lib/python3.5/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'gene_ids_segs' doesn't exist)"
```

This is after I removed all of the "merge...pickle" files in the main output directory (not under the "testing" or "spladder" directories). Should I rerun an earlier step?

Thx,
~Joe

**Comment by akahles** [comment]
Hi Joe,

you mean re-running after updating to version 2.3.0? (Just checking, as your path still has 2.2.3 in the name). Also, please make sure to delete `spladder/*.count.hdf5` in your SplAdder directory, as this is the file that was wrongly built in the previous version.

Cheers,
Andre

**Comment by jfass** [comment]
Ha - yes! I updated, but didn't bother to change the name of the venv directory ... but maaaaybe I'll just redo the venv, just to be on the safe side. And then ... must have been the initial, "qmode single" step that produced the count.hdf5 files? I remove them and rerun ... thanks again, I'll post again with the outcome of that.

**Comment by jfass** [comment]
Update: almost all chromosomes have finished, and I'm getting gff3 and txt.gz, etc., files for all event types _except_ for mult_exon_skip ... this is the error (same for all chromosomes that have finished so far):

```
$ cat chr7.eventCalling.err 
Traceback (most recent call last):
  File "/home/ubuntu/spladder/spladder-2.3.0-venv/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/spladder/spladder-2.3.0-venv/lib/python3.5/site-packages/spladder/spladder.py", line 188, in main
    options.func(options)
  File "/home/ubuntu/spladder/spladder-2.3.0-venv/lib/python3.5/site-packages/spladder/spladder_build.py", line 253, in spladder
    analyze_events(options, options.event_types[e_idx])
  File "/home/ubuntu/spladder/spladder-2.3.0-venv/lib/python3.5/site-packages/spladder/alt_splice/analyze.py", line 89, in analyze_events
    events_all = pickle.load(open(fn_out, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'spladder_out.chr7/merge_graphs_mult_exon_skips_C0.pickle'
```

There's a confirmed multi-exon skip on chr7 in one of the samples that I'm looking for, in particular (and SplAdder found in a three-sample set, previously). Too much of a coincidence for all mult_exon_skip events to fail, anyway ... any chance there's a remaining bug wrt this event?

~Joe

**Comment by akahles** [comment]
Hi Joe,

Could you please check your command line? What I am surprised by is that the missing file name contains `mult_exon_skips` (with an s in the end), while it should only be `mult_exon_skip`. I could not find a misspelling in the code.

Cheers,
Andre

**Comment by jfass** [comment]
Argh! That's got to be it. Sorry ... and thanks for spotting that.
~Joe
